name: cat_p2p_server
description: CAT ephemeral presence and WebSocket signaling server.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0